// <auto-generated />
namespace FinalProjectMain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class step79 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(step79));
        
        string IMigrationMetadata.Id
        {
            get { return "201908011911112_step79"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
